name: Auto Merge Main to Demo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  merge-main-to-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

      - name: Merge main to demo
        run: |
          # Try to checkout existing demo branch, create if doesn't exist
          git checkout demo 2>/dev/null || git checkout -b demo
          
          # Pull latest if the branch exists remotely
          git pull origin demo --no-rebase || true
          
          # Merge with main
          git merge --no-ff main -m "Auto-merge main into demo branch"
          
          # Push changes to demo branch
          git push origin demo
